[build]
builder = "nixpacks"
buildCommand = "cd serviceUploader && npm install"

[deploy]
startCommand = "cd serviceUploader && npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
